[[headers]]
  for = "/Dictionar.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=86400"
